name             'wlc-chef-server'
maintainer       'Michael Koppen'
maintainer_email 'michael.koppen@welovecoing.com'
license          'All rights reserved'
description      'Installs/Configures wlc-chef-server'
long_description 'Installs/Configures wlc-chef-server'
version          '0.1.0'

depends 'tar', '~> 0.6.0'
depends 'git', '~> 4.0.2'
depends 'chef-server', '~> 2.1.6'