name             'knife'
maintainer       'Michael Koppen'
maintainer_email 'michael.koppen@welovecoding.com'
license          'All rights reserved'
description      'Configures knife'
long_description 'Configures knife'
version          '0.1.0'
