# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = '2'
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

Vagrant.require_version '>= 1.6.5'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.hostname = 'wlc-tar-berkshelf'
  if Vagrant.has_plugin?("vagrant-omnibus")
    config.omnibus.chef_version = "12.0.1"
  end

  config.berkshelf.enabled = true

  config.vm.provider "docker" do |d|
    d.privileged = true
    d.volumes = [
      "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    ]
    d.image = "yserz/docker-vagrant-centos-7-minivm_chef"
    d.expose = [22]
    d.has_ssh = true
  end
  
  config.vm.provision :chef_solo do |chef|
    chef.json = {
    }

    chef.run_list = [
      'recipe[wlc-tar::default]'
    ]
  end
end
