---
driver_plugin: vagrant

platforms:
- name: debian-6
  driver_config:
    box: opscode-debian-6.0.7
    box_url: http://opscode-vm.s3.amazonaws.com/vagrant/opscode_debian-6.0.7_chef-11.2.0.box
    require_chef_omnibus: 11.4.0
- name: ubuntu-12.04
  driver_config:
    box: canonical-ubuntu-12.04
    box_url: http://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box
    require_chef_omnibus: true
- name: centos-6.3
  driver_config:
    box: opscode-centos-6.3
    box_url: http://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.3_chef-11.2.0.box

suites:
- name: debian
  run_list: ["recipe[vagrant::default]"]
  excludes: ["centos-5.8", "centos-6.3"]
  attributes:
    vagrant:
      url: http://files.vagrantup.com/packages/a7853fe7b7f08dbedbc934eb9230d33be6bf746f/vagrant_1.2.1_x86_64.deb
      plugins: ["vagrant-omnibus", {name: "vagrant-berkshelf", version: "1.2.0"}]

- name: rhel
  run_list: ["recipe[vagrant::default]"]
  excludes: ["ubuntu-12.04", "debian-6.0.7"]
  attributes:
    vagrant:
      url: http://files.vagrantup.com/packages/a7853fe7b7f08dbedbc934eb9230d33be6bf746f/vagrant_1.2.1_x86_64.rpm
      plugins: ["vagrant-omnibus", {name: "vagrant-berkshelf", version: "1.2.0"}]