name             'wlc-workstation'
maintainer       'Michael Koppen'
maintainer_email 'michael.koppen@welovecoding.com'
license          'All rights reserved'
description      'Installs/Configures wlc-workstation'
long_description 'Installs/Configures wlc-workstation'
version          '0.1.0'

depends 'tar', '~> 0.6.0'
depends 'git', '~> 4.0.2'
depends 'knife', '= 0.1.0'